package com.coderhouse.clientservice.model;


import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Entity class representing a client in the online store system.
 * This class maps to the 'clients' table in the database and includes
 * fields for client details such as name, email, and contact information.
 * <p>
 * The @Data annotation from Lombok automatically generates getters, setters,
 * and other common methods like equals, hashCode, and toString.
 */
@Data
@Entity
@Table(name = "clients")
public class Client {

    /**
     * The unique identifier for the client. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The first name of the client. Cannot be blank and must be less than 55 characters.
     */
    @NotBlank(message = "Name cannot be blank")
    @Size(max = 55, message = "Name must be less than 55 characters")
    @Column(name = "name")
    private String name;

    /**
     * The last name of the client. Cannot be blank and must be less than 55 characters.
     */
    @NotBlank(message = "Last name cannot be blank")
    @Size(max = 55, message = "Last name must be less than 55 characters")
    @Column(name = "last_name")
    private String lastName;

    /**
     * The birth date of the client.
     */
    @Column(name = "birth_date", nullable = false)
    private LocalDateTime birthDate;

    /**
     * The email address of the client. Must be a valid email format and is unique in the system.
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    @Column(name = "email", unique = true)
    private String email;

    /**
     * The physical address of the client. The length must be less than 55 characters.
     */
    @Size(max = 55, message = "Address must be less than 55 characters")
    @Column(name = "address")
    private String address;

    /**
     * The telephone number of the client. The length must be less than 20 characters.
     */
    @Size(max = 20, message = "Telephone must be less than 20 characters")
    @Column(name = "telephone")
    private String telephone;

}
